### ISSUE TITLE
TypeError: Cannot read property 'USER_SPACE_ON_USE' of undefined

### ISSUE THREAD

**Issue by likern** [react-native-svg/react-native-svg#1210]
# Bug
Enums should not be placed to **index.d.ts** files, because they are _not processed_ by Babel.
Now Typescript is used as type-checking in React Native and whole conversion from tsx to js is done by https://babeljs.io/docs/en/next/babel-plugin-transform-typescript. 

This plugin doesn't process *.d.ts files:
> `*.d.ts` files are declaration files, not source files. They are not meant to be parsed by Babel, so you should exclude them.

Link to comment https://github.com/babel/babel/issues/10502#issuecomment-535702204

But Enums are not only types, but are real runtime objects, so they becomes undefined on import.

## Environment info

React native info output:

```bash
likern@likern:~/Breaffy/Smarty$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 213.52 MB / 15.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.local/opt/node-v12.13.1-linux-x64/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.13.1 - ~/Breaffy/Smarty/node_modules/.bin/npm
    Watchman: 4.9.0 - /home/likern/.local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: "react-native-svg": "^**9.13.3**"

## Steps To Reproduce

1. Import EMaskUnits from react-native-svg
2. Use enum member EMaskUnits.USER_SPACE_ON_USE in maskUnits

Describe what you expected to happen:

1. Enum values should be available at runtime

This is a **workaround** code, where Enums are used only for type-checking
```jsx
import Svg, {Mask, Path, G, Rect, Circle, EMaskUnits} from 'react-native-svg';
...
<Mask
      id="Onboarding1_svg__a"
      maskUnits={'useSpaceOnUse' as EMaskUnits.USER_SPACE_ON_USE}
      x={0}
      y={0}
      width={411}
      height={295}>
      <Path fill="#C4C4C4" d="M0 0h411v295H0z" />
</Mask>
```

This is a **invalid** code, where Enums are used **at runtime**.
```jsx
import Svg, {Mask, Path, G, Rect, Circle, EMaskUnits} from 'react-native-svg';
...
<Mask
      id="Onboarding1_svg__a"
      maskUnits={EMaskUnits.USER_SPACE_ON_USE}
      x={0}
      y={0}
      width={411}
      height={295}>
      <Path fill="#C4C4C4" d="M0 0h411v295H0z" />
</Mask>
```

## Reproducible sample code
Repository with reproduction https://github.com/likern/SVGTest

**Helpful links:**
https://lukasbehal.com/2017-05-22-enums-in-declaration-files

![Screenshot_1575318632](https://user-images.githubusercontent.com/842306/69992946-da7c2e00-155b-11ea-9d97-f20a0eea2745.png)

**Comment by likern** [comment]
I haven't added reproducible source code repo because it looks it's trivial to reproduce - just to use `maskUnits={EMaskUnits.USER_SPACE_ON_USE}` on `Mask` element.

**Comment by msand** [comment]
Thanks for reporting, would you mind making a pr to fix this?

**Comment by simistern** [comment]
How would I go about solving this issue? Would exporting the enum from a ts declaration file work?

**Comment by likern** [comment]
> How would I go about solving this issue? Would exporting the enum from a ts declaration file work?

Workaround is already provided in the original message

**Comment by simistern** [comment]
@likern yes I see :) I am just trying to figure out how I would go about solving this issue via a PR, and allow users to use:  

`maskUnits={EMaskUnits.USER_SPACE_ON_USE}`

in the correct way

**Comment by likern** [comment]
> @likern yes I see :) I am just trying to figure out how I would go about solving this issue via a PR, and allow users to use:
> 
> `maskUnits={EMaskUnits.USER_SPACE_ON_USE}`
> 
> in the correct way

I think `EMaskUnits` and other enums should be moved into index.ts (or another ts file). And it should be usual enums, existing in runtime (not `const enums`).
And they should be re-exported in *.d.ts to be visible aa types (probably?)

**Comment by msand** [comment]
Should probably import the units from /src/lib/units.ts into src/ReactNativeSVG.ts and export it from there, and also to use that type in all the places where `'objectBoundingBox' | 'userSpaceOnUse'` is used:

https://github.com/react-native-community/react-native-svg/search?q=objectBoundingBox&unscoped_q=objectBoundingBox

https://github.com/react-native-community/react-native-svg/search?q=userSpaceOnUse&unscoped_q=userSpaceOnUse

**Comment by tatva-hiral** [comment]
Getting same error, TypeError: Cannot read property 'USER_SPACE_ON_USE' of undefined
I have svg format like : 

`
<Svg
      width={218}
      height={244}
      viewBox="0 0 218 244"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <Path
        d="M173.137 175.474l-.939 1.088s-11.414 1.07-10.95 2.919c.463 1.849 13.741-2.466 13.741-2.466l-1.852-1.541z"
        fill="#FFC1C7"
      />
      <Path
        d="M193.827 174.55s-12.198 4.314-18.837 2.465l3.088 6.164s15.749-.462 18.528-3.236c2.779-2.773-2.779-5.393-2.779-5.393z"
        fill="#76659C"
      />
      <Path
        d="M185.566 141.499c4.52 0 8.183-3.657 8.183-8.167s-3.663-8.167-8.183-8.167c-4.519 0-8.183 3.657-8.183 8.167s3.664 8.167 8.183 8.167z"
        fill="#FFC1C7"
      />
      <Path
        d="M192.544 140.999a6.35 6.35 0 001.06 1.467 13.375 13.375 0 003.945 2.945 134.861 134.861 0 01-14.055 2.086c.498-1.751-.157-3.623-1.039-5.217-.881-1.593-2.005-3.078-2.556-4.813l5.531.148c1.004.027 2.011.057 3.014.008.75-.036 1.999-.485 2.699-.32 1.48.35.755 2.386 1.401 3.696z"
        fill="#FFC1C7"
      />
      <Path
        d="M211.12 179.327l4.632 5.547s7.72 18.028-9.11 19.877c-16.83 1.849-29.336-1.387-29.336-1.387s-6.794-3.236-6.949-.77c-.154 2.465-.772 9.399-4.477 16.179l-3.243 7.396s-1.698 1.695-1.235 4.006c.463 2.311-10.345 3.082-10.19 0 0 0 1.544-2.62 1.544-4.16 0-1.541 2.47-5.239 2.47-5.239l4.478-22.189s-.309-11.402 10.19-9.245c10.5 2.157 25.477-.462 25.477-.462l3.397-11.865 12.352 2.312z"
        fill="#2F2E41"
      />
      <Path
        opacity={0.1}
        d="M211.12 179.327l4.632 5.547s7.72 18.028-9.11 19.877c-16.83 1.849-29.336-1.387-29.336-1.387s-6.794-3.236-6.949-.77c-.154 2.465-.772 9.399-4.477 16.179l-3.243 7.396s-1.698 1.695-1.235 4.006c.463 2.311-10.345 3.082-10.19 0 0 0 1.544-2.62 1.544-4.16 0-1.541 2.47-5.239 2.47-5.239l4.478-22.189s-.309-11.402 10.19-9.245c10.5 2.157 25.477-.462 25.477-.462l3.397-11.865 12.352 2.312z"
        fill="#000"
      />
      <Path
        d="M193.749 178.921s14.128-5.295 22.003 5.953c0 0 2.007 17.411-6.022 18.182-8.029.77-18.528.616-20.999-2.003-2.47-2.62-18.065-10.016-18.065-10.016s-7.763-3.951-9.285 1.183c-1.523 5.135-1.677 6.367-1.677 6.367s-8.029 5.856-11.272 6.934c0 0-2.162 3.082-3.397 3.082-1.235 0-8.801 1.695-8.029-4.006l12.507-11.403 12.507-12.172s3.551-5.239 12.661-2.466a188.677 188.677 0 0018.373 4.469l.695-4.104z"
        fill="#2F2E41"
      />
      <Path
        d="M144.881 207.987s3.243 7.242-2.007 6.625c-5.25-.616-9.264-1.695-10.808-1.849-1.485-.148-5.685-1.579-5.041-4.431a2.5 2.5 0 00.042-.56c0-.382.521-1.134 4.69-1.018 0 0 3.088 0 4.323-2.157 0 0 4.632 5.855 8.801 3.39zM161.795 229.576s6.038 5.148 1.032 6.845c-5.005 1.698-9.094 2.448-10.555 2.971-1.405.504-5.812 1.015-6.455-1.837a2.469 2.469 0 00-.202-.524c-.164-.345-.016-1.248 3.798-2.933 0 0 2.789-1.326 2.978-3.805 0 0 6.698 3.299 9.404-.717z"
        fill="#CBCEDA"
      />
      <Path
        d="M179.931 146.352s11.117-6.933 20.381 0c9.264 6.934 15.44 38.522 15.44 38.522l-21.462-4.777s-.926-3.698-2.162-4.314c-1.235-.617-1.389-3.236-1.389-3.236s-6.639-2.003-6.176-9.707c.463-7.705-4.632-16.488-4.632-16.488z"
        fill="#76659C"
      />
      <Path
        d="M185.643 146.66h-5.712s-3.397 3.853-3.861 13.56l-1.852 7.704s-3.86 9.245-1.544 10.786c2.316 1.541 6.793 1.387 7.72-1.695.926-3.081 7.257-20.955 7.257-20.955l-2.008-9.4z"
        fill="#76659C"
      />
      <Path
        d="M184.006 122.704a8.286 8.286 0 018.557 1.4c2.965 2.641 3.563 6.949 4.313 10.844.75 3.895 2.258 8.233 5.936 9.734a15.52 15.52 0 01-4.983-.144l5.559 4.971-9.365-3.046c-2.939-.956-6.025-1.924-9.069-1.384-5.042.894-8.552 5.624-13.395 7.286l.539-2.621-3.249-.024a6.35 6.35 0 001.861-2.177 1.819 1.819 0 00-.555-.45 1.824 1.824 0 00-.688-.199c-1.354-8.43 3.662-16.764 10.2-22.271 1.286-1.084 2.708-2.124 4.369-2.395 1.661-.271 3.6.47 4.177 2.047"
        fill="#2F2E41"
      />
      <Circle cx={166.059} cy={51.255} r={50.33} fill="#E6E6E6" />
      <Circle cx={166.058} cy={30.685} r={20.57} fill="#fff" />
      <Path
        d="M189.387 56.191H142.73v2.282h46.657V56.19zM189.387 62.621H142.73v2.282h46.657V62.62zM189.387 69.05H142.73v2.282h46.657v-2.281zM189.387 75.48H142.73v2.282h46.657v-2.281zM189.387 81.91H142.73v2.282h46.657v-2.281z"
        fill="#fff"
      />
      <Mask
        id="prefix__a"
        maskUnits="userSpaceOnUse"
        x={145}
        y={10}
        width={42}
        height={42}
      >
        <Circle cx={166.058} cy={30.685} r={20.57} fill="#fff" />
      </Mask>
      <G mask="url(#prefix__a)">
        <Path
          d="M154.106 34.854a6.135 6.135 0 011.68-.841 42.941 42.941 0 0111.842-2.573c3.521-.249 7.338.047 10.088 2.256.428.313.778.72 1.023 1.19.346.744.241 1.61.129 2.424a2.728 2.728 0 01-.235.913c-.37.703-1.282.95-2.073.865-.791-.084-1.534-.418-2.315-.573a10.362 10.362 0 00-1.462-.149l-4.895-.264c-3.045-.165-6.13-.327-9.116.287a9.098 9.098 0 00-2.634.905c-.682.382-1.141.93-1.774.225-1.112-1.24-1.727-3.52-.258-4.665z"
          fill="#2F2E41"
        />
        <Path
          d="M161.693 37.015s6.585-2.946 9.083.453c2.497 3.4-1.363 2.04-1.363 2.04l-4.314 1.36-4.769-.907 1.363-2.946z"
          fill="#F2F2F2"
        />
        <Path
          d="M162.033 34.862s.909 4.305.227 5.438c-.681 1.134 3.861 2.72 3.861 2.72l4.314-1.813s-1.135-7.025 0-8.385l-8.402 2.04z"
          fill="#FFB9B9"
        />
        <Path
          opacity={0.1}
          d="M162.033 34.862s.909 4.305.227 5.438c-.681 1.134 3.861 2.72 3.861 2.72l4.314-1.813s-1.135-7.025 0-8.385l-8.402 2.04z"
          fill="#000"
        />
        <Path
          d="M172.479 30.556a6.8 6.8 0 01-1.997 4.806 6.826 6.826 0 01-6.026 1.884 6.8 6.8 0 01-5.375-4.95 6.786 6.786 0 012.218-6.957 6.817 6.817 0 017.253-.941 6.793 6.793 0 013.927 6.158z"
          fill="#FFB9B9"
        />
        <Path
          d="M176.592 51.255h-21.726l.493-2.134 2.132-9.274 2.465-1.66.002-.003 1.158-.782.576-.388s.34.156.733.367a11.03 11.03 0 01.349.202c.189.109.368.233.537.37l.085.082c.432.431 1.694 2.72 3.781 1.549.105-.058.207-.121.305-.19a15.109 15.109 0 001.553-1.23c.438-.401.723-.71.956-.924a1.5 1.5 0 01.353-.261.672.672 0 01.318-.077c.682 0 1.59 1.359 1.59 1.359l.027.079.002.006 2.866 8.587 1.445 4.322z"
          fill="#F2F2F2"
        />
        <Path
          d="M154.867 51.255h6.584c.015-.76-.025-1.52-.119-2.273-.201-1.516-.696-2.977-1.008-4.474a18.837 18.837 0 01-.397-3.99c.003-.185.007-.372.023-.559.017-.427.14-.844.36-1.21.156-.24.37-.443.536-.67a1.51 1.51 0 00.152-.24v-.001a.991.991 0 00.118-.436c.038-.684-.584-1.344-1.255-1.626a4.702 4.702 0 00-2.941-.118c-.959.276-1.886.655-2.764 1.128-.297.145-.593.295-.877.46a4.34 4.34 0 00-.929.706c-.707.728-1.017 1.742-1.266 2.723a5.747 5.747 0 00-.239 2.323c.002.025.008.052.012.077.248 1.292 1.303 2.263 1.867 3.453.652 1.382.609 2.991.349 4.497a9.285 9.285 0 01-.042.23h1.836zM181.669 42.957a51.262 51.262 0 00-1.793 8.298h-9.386c-.246-.668-.49-1.336-.734-2.006a14.927 14.927 0 01-.501-1.543 7.41 7.41 0 01-.191-2.317c.057-.789.24-1.564.542-2.296.139-.332.299-.656.478-.968.437-.788.965-1.53 1.435-2.302.292-.472.547-.966.762-1.477l.001-.004.001-.002a5.29 5.29 0 00.431-2.064c-.015-.915-1.565-2.51.12-2.356 2.301.207 4.277 1.528 6.079 3.034.481.402.95.82 1.41 1.23.71.639 1.461 1.336 1.675 2.267.034.148.054.3.06.452a6.186 6.186 0 01-.389 2.054z"
          fill="#2F2E41"
        />
        <Path
          d="M167.601 40.455a5.055 5.055 0 00-1.066-1.715 3.954 3.954 0 00-1.628-.823 8.912 8.912 0 00-2.388-.341c-.961-.006-2.076.251-2.485 1.12-.324.69-.073 1.507.254 2.196.139.357.372.67.673.908.415.28.951.27 1.443.364.762.193 1.484.52 2.132.964l1.685 1.017 2.893 1.745c-.077-.046-.049-2.026-.138-2.35-.287-1.046-.931-2.095-1.375-3.085z"
          fill="#FFB9B9"
        />
        <Path
          d="M172.307 27.013a1.724 1.724 0 00-.75-.977 3.958 3.958 0 00-.158-1.289c-.413-1.217-1.39-1.147-2.312-1.685-.4-.234-.376-.44-.584-.824a3.06 3.06 0 00-1.18-1.2c-.591-.377-1.216-.764-1.916-.812-1.47-.1-2.598 1.28-4.004 1.724-.619.195-1.285.203-1.908.388-.623.184-1.244.625-1.337 1.267-.043.296.032.6-.011.896-.086.589-.604 1.001-.95 1.486-.767 1.07-.679 2.583-.066 3.748.129.241.277.472.442.69.051.55.209 1.086.466 1.576.613 1.165 1.667 2.036 2.768 2.76a6.57 6.57 0 01-.163-1.177.822.822 0 01.05-.39c.123-.256.447-.324.694-.464.512-.29.713-.933.727-1.52.015-.587-.109-1.176-.048-1.76a.967.967 0 01.33-.707c.189-.108.405-.16.622-.148 1.049-.043 2.144-.062 3.069-.557.299-.198.619-.36.956-.482.786-.205 1.589.345 2.042 1.018.453.673.679 1.474 1.097 2.169.418.695 1.141 1.315 1.949 1.233a.326.326 0 00.241-.107.367.367 0 00.045-.206l.045-3.083a4.655 4.655 0 00-.156-1.567zM154.34 47.603c.148 1.213.237 2.43.269 3.652h-5.716v-4.793c.029-.116.06-.23.098-.345.357-1.099 1.108-2.02 1.758-2.976.031-.048.064-.095.096-.143.276-.403.514-.832.71-1.28.094-.22.244-1.284.402-1.375.677-.392 1.228 1.284 1.321 1.657.333 1.33.622 2.672.84 4.026.085.525.159 1.05.222 1.577zM183.224 51.255h-13.121c-.112-.263-.222-.527-.339-.788a23.038 23.038 0 00-3.146-5.15 1.361 1.361 0 01-.389-.77.655.655 0 01.085-.346c.2-.371.728-.59 1.156-.765a3.988 3.988 0 001.201-.755c.311-.28.55-.63.694-1.023.039-.115.068-.233.088-.352l.182.238c.148.195.298.388.449.58 1.455 1.865 3.054 3.703 5.063 4.809a8.52 8.52 0 001.655.703.431.431 0 00.349 0 .423.423 0 00.152-.278c.178-.747.241-1.516.372-2.273.24-1.378.703-2.707 1.369-3.937.372-.69 1.582-3.215 2.349-1.624l.665 1.38c.139.292.281.582.422.874.521.928.759 1.988.684 3.05l.06 6.427z"
          fill="#2F2E41"
        />
        <Path
          opacity={0.1}
          d="M154.866 51.255h1.137l-.644-2.134-.929-3.076a9.896 9.896 0 01-.09 1.557 10.353 10.353 0 01-.906 3.079c-.089.188-.185.38-.262.574h1.694zM178.024 44.696c-.16.43-.015.905.108 1.346.358 1.28.525 2.607.496 3.936a.152.152 0 01-.002.07.146.146 0 01-.096.098.142.142 0 01-.07.004c-.524.032-1.124.035-1.48-.35l1.044-5.104z"
          fill="#000"
        />
      </G>
      <Circle cx={51.124} cy={51.255} r={50.33} fill="#E6E6E6" />
      <Circle cx={51.123} cy={30.686} r={20.57} fill="#F2F2F2" />
      <Path
        d="M74.452 56.191H27.795v2.282h46.657V56.19zM74.452 62.621H27.795v2.282h46.657V62.62zM74.452 69.051H27.795v2.282h46.657V69.05zM74.452 75.48H27.795v2.282h46.657v-2.281zM74.452 81.91H27.795v2.282h46.657v-2.281z"
        fill="#fff"
      />
      <Mask
        id="prefix__b"
        maskUnits="userSpaceOnUse"
        x={30}
        y={10}
        width={42}
        height={42}
      >
        <Circle cx={51.123} cy={30.686} r={20.57} fill="#F2F2F2" />
      </Mask>
      <G mask="url(#prefix__b)">
        <Path
          d="M43.6 30.63a.51.51 0 00.598-.246c.48-.755-.404-1.728-.212-2.601.153-.7.95-1.115 1.112-1.813.159-.677-.329-1.441 0-2.055.259-.48.904-.607 1.444-.523.54.085 1.052.322 1.597.355.727.044 1.42-.275 2.13-.434.71-.158 1.578-.096 1.996.499.536.764-.008 1.827.179 2.741.148.726.757 1.327.77 2.068.005.263-.689.051-.652.312.037.26-.29.031-.029 0a.52.52 0 00.395-.468c.03-.217.44-.29.435-.509-.011-.514.92-.167 1.073-.658a4.967 4.967 0 00-.203-3.472 6.944 6.944 0 01-.594-1.412c-.137-.682.078-1.413-.148-2.07-.304-.887-1.31-1.339-2.244-1.43-.934-.092-1.883.072-2.812-.063-.832-.121-1.637-.481-2.476-.43-1.007.063-1.884.71-2.582 1.438-.698.727-1.29 1.563-2.083 2.186a4.079 4.079 0 00-.667.573c-.404.492-.445 1.191-.333 1.816.113.625.357 1.222.46 1.849.097.589.067 1.19.109 1.786.01.6.192 1.186.525 1.686a1.594 1.594 0 001.24.647c.169.004.31-.147.48-.108.212.05.305.25.493.337z"
          fill="#2F2E41"
        />
        <Path
          d="M35.968 51.255c.151-2.076.266-3.627.266-3.627l.98-2.58 3.15 6.207h-4.396z"
          fill="#575A89"
        />
        <Path
          d="M43.265 30.842S46.2 38.3 44.51 39.72c-1.69 1.42 9.431-2.398 9.431-2.398l-.267-.976s-3.648-1.421-1.868-5.505c1.78-4.085-8.541 0-8.541 0z"
          fill="#A0616A"
        />
        <Path
          opacity={0.1}
          d="M65.657 51.255h-7.045c-.537-3.924-.98-8.027-.98-8.027l1.425-.622 2.893-1.553s.212.502.552 1.356c.728 1.827 2.048 5.266 3.155 8.846zM35.968 51.255c.151-2.076.266-3.627.266-3.627l.98-2.58 3.15 6.207h-4.396zM43.265 30.842S46.2 38.3 44.51 39.72c-1.69 1.42 9.431-2.398 9.431-2.398l-.267-.976s-3.648-1.421-1.868-5.505c1.78-4.085-8.541 0-8.541 0z"
          fill="#000"
        />
        <Path
          d="M47.446 33.86c3.44 0 6.228-2.782 6.228-6.215 0-3.432-2.788-6.215-6.228-6.215s-6.228 2.783-6.228 6.215c0 3.433 2.789 6.216 6.228 6.216z"
          fill="#A0616A"
        />
        <Path
          d="M62.571 41.053l-.068 1.356c-.09 1.757-.25 5.049-.41 8.846H37.951a11.94 11.94 0 01-1.536-2.744 2.956 2.956 0 01-.181-.883c-.133-2.355 1.98-5.64 3.473-5.953 1.69-.357 4.892-3.73 4.892-3.73a.76.76 0 00.408.615v.002c.258.133.547.196.837.182 1.044 0 5.633-2.113 7.106-2.804.29-.135.458-.216.458-.216 1.7.732 3.455 1.327 5.25 1.778a5.588 5.588 0 013.913 3.55z"
          fill="#575A89"
        />
        <Path
          d="M42.533 30.009a.51.51 0 00.597-.246c.48-.755-.403-1.728-.212-2.602.153-.7.95-1.115 1.113-1.812.158-.678-.33-1.442 0-2.055.258-.48.904-.607 1.444-.523.54.084 1.052.32 1.597.354.727.044 1.42-.275 2.13-.433.71-.158 1.577-.096 1.995.498.537.764-.007 1.828.18 2.742.148.726 1.839 1.235 1.992.744a4.968 4.968 0 00-.204-3.472 6.949 6.949 0 01-.594-1.412c-.136-.681.079-1.413-.147-2.07-.304-.887-1.31-1.338-2.244-1.43-.934-.092-1.883.072-2.812-.063-.832-.121-1.638-.48-2.477-.429-1.007.063-1.883.71-2.581 1.437-.698.727-1.29 1.563-2.083 2.186-.242.167-.466.36-.668.574-.403.491-.444 1.19-.332 1.816.112.625.357 1.221.46 1.848.097.59.067 1.19.109 1.786.01.601.192 1.186.525 1.687a1.595 1.595 0 001.24.646c.169.004.31-.146.48-.107.212.05.304.25.492.336z"
          fill="#2F2E41"
        />
        <Path
          d="M66.279 51.255h-7.952c-1.178-4.293-2.34-8.96-2.34-8.96l3.026-2.22 3.558.978S64.654 46 66.28 51.255z"
          fill="#575A89"
        />
      </G>
      <Circle cx={108.821} cy={106.521} r={50.33} fill="#3F3D56" />
      <Circle cx={108.821} cy={85.952} r={20.57} fill="#F2F2F2" />
      <Path
        d="M132.149 111.458H85.493v2.281h46.656v-2.281zM132.149 117.887H85.493v2.282h46.656v-2.282zM132.149 124.317H85.493v2.281h46.656v-2.281zM132.149 130.747H85.493v2.281h46.656v-2.281zM132.149 137.177H85.493v2.281h46.656v-2.281z"
        fill="#76659C"
      />
      <Mask
        id="prefix__c"
        maskUnits="userSpaceOnUse"
        x={88}
        y={65}
        width={42}
        height={42}
      >
        <Circle cx={108.821} cy={85.952} r={20.57} fill="#fff" />
      </Mask>
      <G mask="url(#prefix__c)">
        <Path
          d="M111.309 73.924a5.548 5.548 0 00-5.729.938c-1.985 1.768-2.385 4.652-2.887 7.26-.502 2.607-1.512 5.511-3.974 6.516a10.38 10.38 0 003.336-.097l-4.426 2.47 7.541-.65c1.967-.64 3.466-1.819 5.504-1.457 3.375.599 5.725 3.765 8.967 4.878l-.36-1.755 2.175-.016a4.254 4.254 0 01-1.246-1.457 1.2 1.2 0 01.832-.435c.907-5.644-2.452-11.223-6.828-14.91-.861-.725-1.814-1.422-2.926-1.603-1.111-.182-2.409.315-2.796 1.37"
          fill="#2F2E41"
        />
        <Path
          d="M124.898 106.521h-4.512a36.205 36.205 0 01-.925-2.829 5.646 5.646 0 00-1.472-2.993 5.553 5.553 0 01-.633-.859 4.02 4.02 0 01-.399-2.445c.025-.233.064-.464.116-.693.197-.886.528-1.736.804-2.599a.987.987 0 01.807-.666c.297-.05.603-.014.881.102.061.025.121.055.177.091.492.297.748.903.954 1.456a24101.082 24101.082 0 013.371 9.039 41.1 41.1 0 01.767 2.18l.064.216z"
          fill="#D0CDE1"
        />
        <Path
          d="M107.152 84.972s.131 3.932-.263 4.325c-.394.393 1.576 3.014 1.576 3.014l3.546-.13 1.838-1.442-1.576-2.097s-.656-3.407-.131-4.194c.525-.786-4.99.524-4.99.524z"
          fill="#E6C8CC"
        />
        <Path
          d="M109.319 86.48a4.722 4.722 0 004.727-4.719 4.722 4.722 0 00-4.727-4.718 4.723 4.723 0 00-4.728 4.718 4.722 4.722 0 004.728 4.718z"
          fill="#FFE4E8"
        />
        <Path
          d="M111.742 106.521h3.832c.144-.259.279-.529.435-.774v-.002c.17-.296.41-.546.698-.73a2.77 2.77 0 00.518-.309 1.33 1.33 0 00.315-.589 9.12 9.12 0 00.433-2.543c.006-.29 0-.585.016-.875.009-.227.038-.453.088-.674a5.28 5.28 0 01.567-1.282c.52-.944 1.041-1.887 1.563-2.831.094-.266.13-.549.106-.83a2.04 2.04 0 00-.337-1.064 5.514 5.514 0 00-.235-.388 8.592 8.592 0 00-1.114-1.418 9.007 9.007 0 00-3.171-2.143 1.823 1.823 0 01-.426-.207 1.75 1.75 0 01-.391-.467c-.416-.624-.923-1.328-1.673-1.288a1.028 1.028 0 00-.794-.054c-.039.01-.078.023-.116.037a7.354 7.354 0 00-.834.434c-.69.357-1.472.5-2.244.406a.759.759 0 01-.262-.066 1.31 1.31 0 01-.241-.195 1.391 1.391 0 00-1.378-.22c-.215.076-.405.21-.549.386-.137.172-.233.38-.385.541-.392.42-1.041.436-1.615.434a14.95 14.95 0 00-3.547.325 6.751 6.751 0 00-2.794 1.349l-.002.002a5.446 5.446 0 00-.32.296c-.236.222-.424.49-.553.788-.158.407-.137.865-.28 1.278-.158.463-.51.84-.65 1.305-.109.352-.094.742-.273 1.062l.023.018c.756.664 1.403 1.535 2.161 2.193.44.334.813.75 1.098 1.224.055.106.1.217.135.331.085.397.123.802.112 1.207.096 1.94 1.149 3.699 2.328 5.242.023.031.046.062.07.091h9.686z"
          fill="#D0CDE1"
        />
        <Path
          d="M99.41 99.65c-.178 1.238-.358 2.475-.54 3.712a16.168 16.168 0 01-.37 1.967c-.108.4-.247.792-.345 1.192h-5.412c.003-.224.02-.448.052-.67.14-.797.366-1.577.676-2.325.63-1.696 1.258-3.394 1.887-5.094.268-.724.499-1.48.794-2.198.052-.133.108-.266.168-.394.314-.69 1.185-.407 1.83-.303.176.022.348.07.51.145.196.108.361.263.48.452.611.902.478 2.095.32 3.173l-.05.343z"
          fill="#D0CDE1"
        />
        <Path
          d="M109.712 81.761c2.829 0 5.122-1.232 5.122-2.752 0-1.52-2.293-2.752-5.122-2.752-2.828 0-5.121 1.232-5.121 2.752 0 1.52 2.293 2.752 5.121 2.752z"
          fill="#2F2E41"
        />
      </G>
    </Svg>`

**Comment by ParthPandey2611** [comment]
hey , can any one guide here any begineer friendly issue ?
