### ISSUE TITLE
borderRadius not working

### ISSUE THREAD

**Issue by exotexot** [react-native-svg/react-native-svg#1393]
Hi,

I'm looking to build a button as suggested here: https://github.com/react-native-community/react-native-svg/issues/645

I do need the button to have rounded borders, which is usually achieved through borderRadius. But I dont get it to work with any of the svg elements. Any advice?

**Comment by rmacqueen** [comment]
I have a need for the same thing. Any update on this?

**Comment by iggirex** [comment]
Trying to give a Rect border-radius with this library is way harder than it should be. I've landed at creating a ClipPath with two ovals on either end and a rectangle in the middle. It kinda works but feels very hacky.

There's a few built in props that sound like they'd do the trick, strokeLinecap="round", strokeLinejoin="round". But they don't seem to be doing anything in my case, and I can't find an example of using these props in the docs.

**Comment by iggirex** [comment]
AAAAHH! Just give your Rect the `rx` and `ry` props! Boom you got rounded corners.
Having an example of this in the docs would have saved me hours. If I have some time I'll try adding this in and creating a PR 👍

**Comment by PavanKu** [comment]
Any update on this? I am also try to apply borderRadius to SVG element but its not working.

**Comment by romadryud** [comment]
Any updates?

**Comment by kylanhurt** [comment]
Also need help with this! Why does `overflow: 'hidden'` not work for the wrapping <View>?

**Comment by J6ey** [comment]
I can set the border radius by styling View and wrapping the SVG element in it.

**Comment by RahulMore-Codes** [comment]
> 

what if only a specific corner needs to be rounded?

**Comment by shahbazshueb** [comment]
setting rx and ry worked for me

**Comment by ShivamJoker** [comment]
rx tx makes the entire SVG invisible I am not sure what am I doing wrong.
