### ISSUE TITLE
Improve performance of an app using SVG.

### ISSUE THREAD

**Issue by german-schneck** [react-native-svg/react-native-svg#1397]
**Good morning, everyone.**

I am writing to comment on a question that has arisen because of a performance problem in an app I am developing.

I happen to have 15 small images that load in a FlatList, this caused the app to take between 1 or 2 seconds each time I navigated to the screen where the list was rendered.

My question is, **what tips can you give me to optimize and improve the performance of the app?**

Initially I thought about pre-caching the images, but I don't have much idea if it's possible in this kind of files.

Thank you very much!

**Comment by tastafur** [comment]
+ 1

**Comment by akshgods** [comment]
+1

**Comment by minafa96** [comment]
I have the same issue. any updates?

**Comment by gebo96** [comment]
> I have the same issue. any updates?

In the end the problem was because it was not an SVG itself, but a PNG framed in a base64 inside an svg file.  things of the designers haha

If you have the same problem, check that it is not that. **Good luck!**

**Comment by douglasjunior** [comment]
Same here.

We are using `react-native-svg@12.1.1` and `react-native-svg-transformer:0.14.3`, and we have a `FlatList` that loads infinite items that have one of [these SVG images](https://github.com/react-native-svg/react-native-svg/files/7187522/Archive.zip).

But we are having serious performance issues on iOS (Android is fine), where navigating from one screen to another takes 1 or 2 seconds. 

I tried to use a `memo` wrapping the Item and the SVG componente, but it makes no difference.

Our list is paging, loading 25 per page.

**Comment by douglasjunior** [comment]
> > I have the same issue. any updates?
> 
> In the end the problem was because it was not an SVG itself, but a PNG framed in a base64 inside an svg file. things of the designers haha
> 
> If you have the same problem, check that it is not that. **Good luck!**

You're right, I just looked at it now and noticed that inside there is a base64 PNG file .

**Comment by WoLewicki** [comment]
Can we close this issue then? Seems like it is not the fault of `react-native-svg`.

**Comment by WoLewicki** [comment]
I will close it then. Feel free to comment here if something is wrong and we can always reopen it.

**Comment by witherBattler** [comment]
> > I have the same issue. any updates?
> 
> In the end the problem was because it was not an SVG itself, but a PNG framed in a base64 inside an svg file. things of the designers haha
> 
> If you have the same problem, check that it is not that. **Good luck!**

For me I literally don't have a choice, as I need to render the png base64 in an image in a pattern, and use that pattern in ~40 paths. I have this written in react on the web, and it works without problem (even on mobile) but on react native it crashes everytime. What can I do?
