### ISSUE TITLE
Error while updating property 'fill' of a view managed by: RNSVGPath

### ISSUE THREAD

**Issue by FrancoMuniz** [react-native-svg/react-native-svg#1405]
I'm having this issue, saw that the exact same issue was solved time ago, but the solution is not working for me.

# Bug

After installing react-native-svg using "expo install react-native-svg", I try to add the following Svg:

```
<Svg width={18} height={20} viewBox="0 0 18 20" >
      <G
        transform="translate(1 1)"
        stroke="#000"
        strokeWidth={2}
        fill="none"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <Path d="M16 18v-2a4 4 0 00-4-4H4a4 4 0 00-4 4v2" />
        <Circle cx={8} cy={4} r={4} />
      </G>
</Svg>
```
and this error shows up:

```
Error while updating property 'fill' of a view managed by: RNSVGPath

null

java.lang.Double cannot be cast to java.lang.String
```

Tried uninstalling and installing several versions. Same thing with all of them.
Current one: 9.13.3

**Comment by edencorbin** [comment]
same issue here.

**Comment by raymelon** [comment]
Having the same issue as well.

```json
"react": "16.13.1",
"react-native": "0.63.1",
"react-native-svg": "12.0.3",
```

I use fortawesome svg pacakges, could be conflicting with `react-native-svg` on some degree. I need to investigate further to confirm.

```json
"@fortawesome/fontawesome-svg-core": "^1.2.30",
"@fortawesome/free-brands-svg-icons": "^5.14.0",
"@fortawesome/free-regular-svg-icons": "^5.14.0",
"@fortawesome/free-solid-svg-icons": "^5.14.0",
"@fortawesome/react-native-fontawesome": "^0.2.5",
"@react-native-community/masked-view": "^0.1.10",
```

**Comment by raymelon** [comment]
> Having the same issue as well.
> 
> ```json
> "react": "16.13.1",
> "react-native": "0.63.1",
> "react-native-svg": "12.0.3",
> ```
> 
> I use fortawesome svg pacakges, could be conflicting with `react-native-svg` on some degree. I need to investigate further to confirm.
> 
> ```json
> "@fortawesome/fontawesome-svg-core": "^1.2.30",
> "@fortawesome/free-brands-svg-icons": "^5.14.0",
> "@fortawesome/free-regular-svg-icons": "^5.14.0",
> "@fortawesome/free-solid-svg-icons": "^5.14.0",
> "@fortawesome/react-native-fontawesome": "^0.2.5",
> "@react-native-community/masked-view": "^0.1.10",
> ```

Giving an update, I was able to solve the issue by using the Expo's version of the package. That worked for me because I only use `react-native-svg` as a prerequisite for fontawesome packages.

```json
"react-native-svg": "git+https://github.com/expo/react-native-svg"
```

**Comment by ChuksFestus** [comment]
Has anyone found a fix for this yet?

**Comment by da8636** [comment]
This is still a persisting issue and have not found a solution. Any advice would be appreciated.

**Comment by shay-te** [comment]
experiencing the same issue. while installing (https://github.com/skrafft/react-native-jitsi-meet#android-install)[https://github.com/skrafft/react-native-jitsi-meet#android-install]

**Comment by masarapu4848** [comment]
i get the same issue and using 
  "react": "16.13.1"
   "react-native": "0.63.4",
    "react-native-svg": "12.0.3",

and i tried using "react-native-svg": "git+https://github.com/expo/react-native-svg.git"
 or 
  "react-native-svg": "9.13.1",

still i get the same error

**Comment by Hayoung079** [comment]
l have same error. 
"react": "17.0.1",
"react-native": "0.64.0",
"react-native-svg": "12.0.3"

and i tried using "react-native-svg": "git+https://github.com/expo/react-native-svg.git", "react-native-svg": "9.13.1",

still i get the same error.

did you solve it?

There was no error until yesterday, but now it doesn't.

**Comment by ecemac** [comment]
Still having the same error, any updates on this issue?

**Comment by yasir-systemplus** [comment]
Any update on this issue? I am having still same problem.

**Comment by hugoh59** [comment]
Same issue on android only.

**Comment by MaymoonaAlBoloshi** [comment]
👀 any update on this?

**Comment by gabrielvrl** [comment]
any updates on this?

**Comment by christopherboisvert** [comment]
I have the same problem here !

Here is my dependencies:
`
{
  ""dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-navigation/drawer": "^6.4.4",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "expo": "~46.0.8",
    "expo-dev-client": "~1.2.1",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-reanimated": "2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "3.15.0",
    "react-native-svg": "^13.1.0",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "react-native-svg-transformer": "^1.0.0"
  },
}
`

**Comment by mateusfranco** [comment]
if you are using expo, sometimes when you run yarn start you will see a message like "react-native-svg V-XX.X.X" is incompactible with expo, install version XX.X.X 

So i only change the version of react-native-svg and delete and install dependences again

**Comment by RamboGj** [comment]
Hey guys! I was having the same issue here. Try installing react-native-svg packages again, it worked for me
1 - stop expo app 
`expo install react-native-svg`
2 - rerun the app

**Comment by PolimacNortik** [comment]
> 

After rerunning the app it showed a warning that my react-native-svg version is incompatible with the installed expo version and after installing the expected version it was fixed.

**Comment by WoLewicki** [comment]
I think it should be resolved in `expo` as well as for bare apps in the newest version of the library. I will close this issue then. Feel free to comment here with repro if something is wrong and we can always reopen it then.

**Comment by tier3guy** [comment]
Still having the same issue. If it is resolved than any kind of reference would be appreciated.

**Comment by tier3guy** [comment]
Installing  react-native-svg@9.13.6, this particular version worked for me.

**Comment by tsheaff** [comment]
Thanks @tier3guy this saved me from this issue. A bit frustrating that we have to be 4 major versions behind just to get it working on Android, but this did solve the `Error while updating property 'fill'` crash for me.

**Comment by dylan-westbury** [comment]
Make sure no outdated version installed or different duplicate versions.

clear node_modules and package.lock / yarn.lock

**Comment by bzozoo** [comment]
V12.3.0 is work for me
