### ISSUE TITLE
Please add support for react-native-macos and react-native-windows.

### ISSUE THREAD

**Issue by aschick82** [react-native-svg/react-native-svg#1426]
# Feature Request

Is there any plan for supporting the following 2 new extensions?

react-native-macos
react-native-windows

**Comment by ospfranco** [comment]
regarding react-native-macos:

I know almost nothing of obj-c and xcode, but I had luck porting react-native-sqlite2 to macos, so I thought I might also get somewhere with this package.

however, as expected this library relies heavily on UIKit and UIViews which are not quite the same as NSViews used in macos, so this goes a little beyond my head, I added some macros to import Appkit instead of UIKit, yet at some point compilation fails (as expected)

maybe who actually knows what to do can take over and finish the work:
https://github.com/ospfranco/react-native-svg

**Comment by ospfranco** [comment]
original ticket seems to be #297, there were some discussions last year, but it seems like there has been no news, I can also see the repo is not very active... so I wouldn't hold my breath for this...

**Comment by RockyF** [comment]
> regarding react-native-macos:
> 
> I know almost nothing of obj-c and xcode, but I had luck porting react-native-sqlite2 to macos, so I thought I might also get somewhere with this package.
> 
> however, as expected this library relies heavily on UIKit and UIViews which are not quite the same as NSViews used in macos, so this goes a little beyond my head, I added some macros to import Appkit instead of UIKit, yet at some point compilation fails (as expected)
> 
> maybe who actually knows what to do can take over and finish the work:
> https://github.com/ospfranco/react-native-svg

sadly, your copy could not compile successfully with error:
`(132, 1) Property with 'retain (or strong)' attribute must be of object type`
you should update you macos version to 10.10 or newer.

**Comment by ospfranco** [comment]
@RockyF I know... that is why I said... compilation fails, somebody needs to take over, did you not read my comment and just click on my fork?

**Comment by RockyF** [comment]
> @RockyF I know... that is why I said... **compilation fails, somebody needs to take over**, did you not read my comment and just click on my fork?

Sorry for my recklessness. I thought your fork was ready for use.

**Comment by ospfranco** [comment]
not stale

**Comment by x-ji** [comment]
While Googling around I saw that MS announced that they support SVG natively with React Native for Windows in this post dating to Feb 2020. https://microsoft.github.io/react-native-windows/blog/2020/02/010/m4updates#svg-image-support I guess this library probably provides more flexibility and configuration options?

**Comment by x-ji** [comment]
FYI I think the library already on MacOS as long as the build target is > MacOS 10.14. See this question: https://stackoverflow.com/questions/68510491/react-native-macos-component-exception I also tried it myself and it worked out of the box :)

**Comment by WoLewicki** [comment]
I'm closing this since https://github.com/react-native-svg/react-native-svg/pull/1632 was merged. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by ospfranco** [comment]
#1632 looks like a Window only implementation? Also not sure what x-ji means, maybe he is using catalyst, which is not compatible with pure react-native-macos, since one cannot use UI kit and everything needs to be implemented using AppKit
