### ISSUE TITLE
Error in iOS libraries "library not found for -lRNSVG "

### ISSUE THREAD

**Issue by Luisquii** [react-native-svg/react-native-svg#1469]
Hi,

After installing the library using yarn in my project I did the pod install and I get this error when building on iOS:

"library not found for -lRNSVG"

ld: warning: directory not found for option '-L/Users/.../Debug-iphonesimulator/RNSVG'
ld: library not found for -lRNSVG

My Library search paths:
![Screen Shot 2020-10-04 at 19 25 29](https://user-images.githubusercontent.com/41712573/95030752-6cbafa00-0677-11eb-99cd-217944caa5dd.png)

What can I do to fix this issue?

**Comment by Navipro70** [comment]
Try this one of this:
1. Update package for last version.
2. Delete node_modules and run yarn.
3. Delete package and install then install it.

And check [this](https://stackoverflow.com/questions/24050012/error-library-not-found-for-after-putting-application-in-admob)

**Comment by uplamartya** [comment]
I am facing the same issue in iOS
![Uploading Screenshot 2021-02-25 at 6.13.37 PM.png…]()

**Comment by yozenou** [comment]
@Luisquii Do you find any solution to success the build ? Thanks for the help !

**Comment by davidcort** [comment]
This works for me!!

"react-native": "0.64.2"
Xcode: 12.5.1

Search in node_modules, into the react-native-svg folder, the file RNSVG.podspec and replace the next: 

`s.dependency          'React`

for

`s.dependency          'React-Core`

That does the trick ;)

**Comment by dangtony98** [comment]
Upon installation into my project, I am also running into the same error; I've included a few screenshots below for more detail. 

This is pretty alarming for such a widely used package. Has anyone been able to resolve this?

Error:

<img width="1025" alt="Screen Shot 2021-12-20 at 10 23 22 AM" src="https://user-images.githubusercontent.com/25857006/146790976-e0370476-93bc-4a27-ba63-5fa5389fe53f.png">

System information:

<img width="596" alt="Screen Shot 2021-12-20 at 10 25 43 AM" src="https://user-images.githubusercontent.com/25857006/146791334-478108a7-c46f-4a9e-93e8-cd57079fd93d.png">

**Comment by davidcort** [comment]
@dangtony98 

This works for me!!

"react-native": "0.64.2"
Xcode: 12.5.1

Search in node_modules, into the react-native-svg folder, the file RNSVG.podspec and replace the next:

s.dependency 'React'

for

s.dependency 'React-Core'

That does the trick ;)

**Comment by dangtony98** [comment]
@davidcort Unfortunately that doesn't fix it for me ...

**Comment by davidcort** [comment]
> 

Delete the node_modules and package_lock.json. Clean the project in Xcode and try again.

**Comment by dangtony98** [comment]
@davidcort Nevermind got it; not sure why I didn't try before but cleaning the build folder did the job for me.

Thanks!

**Comment by WoLewicki** [comment]
Since this commit has been released: https://github.com/react-native-svg/react-native-svg/commit/e8ed5e943f761ecfad9fa83e17d08ebe3a694fa0 and based on this comment: https://github.com/react-native-svg/react-native-svg/issues/1469#issuecomment-998041222, I think we can close it. Feel free to comment here if I am wrong and we can always reopen it then.

**Comment by xxidbr9** [comment]
Hii all, im facing this problem, I was try to clear the cache and remove node_modules including yarn.lock, and still got this issue, does anyone know how to solve it?  

i was go to my this dir but sure there is no folder named RNSVG
```base
⚠️  ld: directory not found for option '-L/Users/nando/Library/Developer/Xcode/DerivedData/kontan-bkrulqptxeculoexezvklshxhopi/Build/Products/Debug-iphonesimulator/RNSVG'

❌  ld: library not found for -lRNSVG



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```


btw for note im using M1 and not using resseta for run my project

**Comment by davidcort** [comment]
> Hii all, im facing this problem, I was try to clear the cache and remove node_modules including yarn.lock, and still got this issue, does anyone know how to solve it?
> 
> i was go to my this dir but sure there is no folder named RNSVG
> 
> ```
> ⚠️  ld: directory not found for option '-L/Users/nando/Library/Developer/Xcode/DerivedData/kontan-bkrulqptxeculoexezvklshxhopi/Build/Products/Debug-iphonesimulator/RNSVG'
> 
> ❌  ld: library not found for -lRNSVG
> 
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> btw for note im using M1 and not using resseta for run my project and im using Xcode version 13.4.1

Hi, check my solution. I have a Mac Book with M1 too.

**Comment by xxidbr9** [comment]
> > Hii all, im facing this problem, I was try to clear the cache and remove node_modules including yarn.lock, and still got this issue, does anyone know how to solve it?
> > i was go to my this dir but sure there is no folder named RNSVG
> > ```
> > ⚠️  ld: directory not found for option '-L/Users/nando/Library/Developer/Xcode/DerivedData/kontan-bkrulqptxeculoexezvklshxhopi/Build/Products/Debug-iphonesimulator/RNSVG'
> > 
> > ❌  ld: library not found for -lRNSVG
> > 
> > 
> > 
> > ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > btw for note im using M1 and not using resseta for run my project and im using Xcode version 13.4.1
> 
> Hi, check my solution. I have a Mac Book with M1 too.

i was take a look into the react-native-svg in node_modules, in file file RNSVG.podspec, it was already using

```
s.dependency 'React-Core'
```

here the file

```podspec
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name              = 'RNSVG'
  s.version           = package['version']
  s.summary           = package['description']
  s.license           = package['license']
  s.homepage          = package['homepage']
  s.authors           = 'Horcrux Chen'
  s.platforms         = { :osx => "10.14", :ios => "9.0", :tvos => "9.2" }
  s.source            = { :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => "v#{s.version}" }
  s.source_files      = 'apple/**/*.{h,m}'
  s.ios.exclude_files = '**/*.macos.{h,m}'
  s.tvos.exclude_files = '**/*.macos.{h,m}'
  s.osx.exclude_files = '**/*.ios.{h,m}'
  s.requires_arc      = true
  s.dependency          'React-Core'
end
```

any suggestion?

**Comment by xxidbr9** [comment]
> > > Hii all, im facing this problem, I was try to clear the cache and remove node_modules including yarn.lock, and still got this issue, does anyone know how to solve it?
> > > i was go to my this dir but sure there is no folder named RNSVG
> > > ```
> > > ⚠️  ld: directory not found for option '-L/Users/nando/Library/Developer/Xcode/DerivedData/kontan-bkrulqptxeculoexezvklshxhopi/Build/Products/Debug-iphonesimulator/RNSVG'
> > > 
> > > ❌  ld: library not found for -lRNSVG
> > > 
> > > 
> > > 
> > > ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > btw for note im using M1 and not using resseta for run my project and im using Xcode version 13.4.1
> > 
> > 
> > Hi, check my solution. I have a Mac Book with M1 too.
> 
> i was take a look into the react-native-svg in node_modules, in file file RNSVG.podspec, it was already using
> 
> ```
> s.dependency 'React-Core'
> ```
> 
> here the file
> 
> ```ruby
> require 'json'
> 
> package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
> 
> Pod::Spec.new do |s|
>   s.name              = 'RNSVG'
>   s.version           = package['version']
>   s.summary           = package['description']
>   s.license           = package['license']
>   s.homepage          = package['homepage']
>   s.authors           = 'Horcrux Chen'
>   s.platforms         = { :osx => "10.14", :ios => "9.0", :tvos => "9.2" }
>   s.source            = { :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => "v#{s.version}" }
>   s.source_files      = 'apple/**/*.{h,m}'
>   s.ios.exclude_files = '**/*.macos.{h,m}'
>   s.tvos.exclude_files = '**/*.macos.{h,m}'
>   s.osx.exclude_files = '**/*.ios.{h,m}'
>   s.requires_arc      = true
>   s.dependency          'React-Core'
> end
> ```
> 
> but it only error when im running on simulator, it fine in real device
> 
> any suggestion?

im finally fix it, I removed my project 

```bash
rm -rf ~Library/Developer/Xcode/DerivedData/myproject
```
and do a `pod repo update`, and reinstall it again and it was fixed, thanks for the advice
