### ISSUE TITLE
how can i place a small marker on a Path element?

### ISSUE THREAD

**Issue by nimrodbens** [react-native-svg/react-native-svg#1499]
i drew a curved line from the top of the screen to the bottom of the screen and i want a small avatar image to follow that line. is it possible? thank you.

this is the path i drew:

    <Path
      d={`
        M${pathWidth / 2},0
        C${pathWidth - pathPadding},${pathHeight * 0.25}
        ${pathPadding},${pathHeight * 0.75}
        ${pathWidth / 2},${pathHeight}
      `}
      stroke="black"
      strokeWidth={1}
    >

**Comment by kukuandroid** [comment]
any solution for this ?
