### ISSUE TITLE
Phone dark mode put app SVG to black

### ISSUE THREAD

**Issue by antoine-pous** [react-native-svg/react-native-svg#1509]
# Question
Hi!

I'm facing an issue, currently when I enable my phone Dark mode all white SVG become black.

I would like know how I can disable this behaviours on my app, since it only have a dark mode with white SVG assets.

Thank you

**Comment by antoine-pous** [comment]
Ok, after som researches and tests this solution worked for me, maybe could you update the documentation to cover this case :)

https://stackoverflow.com/questions/57175226/how-to-disable-night-mode-in-my-application-even-if-night-mode-is-enable-in-andr/64339016#64339016

**Comment by diegodorado** [comment]
why is this marked as resolved? why does the svg change its defined color based on darkemode enabled or not?
