### ISSUE TITLE
LinearGradient Stop component is setup in a way that doesn't allow for animation.

### ISSUE THREAD

**Issue by a-eid** [react-native-svg/react-native-svg#1519]
it seems that the `<Stop />`, is just a dummy component that wouldn't allow for (at least UI thread) animations.

**Comment by jaraujocds** [comment]
Same here, did you solve it?

**Comment by a-eid** [comment]
@jaraujocds No, I have not.

**Comment by WoLewicki** [comment]
I believe it is the same problem as #1695 so I will close it to keep the discussion in one place. Feel free to comment here if I am wrong and we can reopen it then.
