### ISSUE TITLE
Module parse failed, possible invalid import from react-native?

### ISSUE THREAD

**Issue by davisk4rpi** [react-native-svg/react-native-svg#1537]
I am using storybook to develop ui components for react native. Webpack is giving me an error due to react-native-svg

```
ERROR in ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 18:12
Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const AssetSourceResolver = require('./AssetSourceResolver');
| 
> import type {ResolvedAssetSource} from './AssetSourceResolver';
| 
| let _customSourceTransformer, _serverURL, _scriptURL;
 @ ./node_modules/react-native-svg/lib/module/LocalSvg.js 1:1802-1860
 @ ./node_modules/react-native-svg/lib/module/ReactNativeSVG.js
 @ ./node_modules/react-native-svg/lib/module/index.js
```
Initially I assumed `react-native/Libraries/Image/resolveAssetSource.js` was the culprate, but after seeing [this](https://github.com/necolas/react-native-web/issues/1812) I believe the problem is here. 

Is there a way for me to fix this or is this actually an invalid import?

**react-native-svg/src/LocalSvg.tsx**
```
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
```

**Comment by AljoschaLipski** [comment]
Hey, did you find any solution for this issue?

**Comment by davisk4rpi** [comment]
> Hey, did you find any solution for this issue?

not yet

**Comment by pratyushok** [comment]
I have hosted my fixed version for the time being here [react-native-svg-fixed](https://www.npmjs.com/package/react-native-svg-fixed).

Hope it helps till a proper fix is merged to the main library.

**Comment by cjpete** [comment]
`Image` now has a method for `resolveAssetSource` - that might work instead of importing it from the internals of react-native?

**Comment by belaziv** [comment]
any updates? any idea?

**Comment by almirfilho** [comment]
> any updates? any idea?

@belaziv I've managed to fix mine doing this https://github.com/react-native-svg/react-native-svg/issues/1553#issuecomment-1011487502
