### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by msand** [react-native-svg/react-native-svg#1554]
As I'm too busy with growing our startup atm, and soon becoming a father, I must concede that I cannot provide the all attention this repo deserves, right now at least. 

Thus I'm announcing that this repository is looking for more maintainers to step in. 

Not sure how to market this properly, if anyone is willing to champion this, or has some suggestions, please comment here. All help is much appreciated and very welcome!

**Comment by safaiyeh** [comment]
hey @msand id love to help out. I help maintain voice & cookies. This is an important repo to the RN community so always happy to ramp up efforts!

**Comment by Ananthakr** [comment]
Hey @msand I would like to help maintain this repo. I have very little experience in maintaining a lib, but I want to get into OSS and contribute to the tools which help me day to day.

**Comment by Naturalclar** [comment]
@msand I'd like to help out as well!

**Comment by zoontek** [comment]
I can help too!

**Comment by Victorvikson1996** [comment]
I can help too

**Comment by ShahrozTanveer** [comment]
@msand I'd like to help

**Comment by ShahrozTanveer** [comment]
@msand I'd love to help

**Comment by guadalupeperezb** [comment]
I can help

**Comment by JesusTheHun** [comment]
Hi @msand 
Following [this](https://github.com/react-native-svg/react-native-svg/issues/1223#issuecomment-804274842) it would be nice if you could open a collective for this repo. Only the owner of the repo can do it so it would be nice of you to open the collective. 
The idea -if you agree- would be for you to handover this project progressively to the collective, so members of this community can carry the project.
We need to organize ourself, raise funds and define objectives.

**Comment by mjgerace** [comment]
Hi, I'd also be more than willing to help with this project.

**Comment by mikolajadamowicz** [comment]
Hi, i'd love to squash some bugs in my free time. Hit me up for anything js/IOS related.

**Comment by shamilovtim** [comment]
Hi,

We're looking to get https://github.com/react-native-svg/react-native-svg/pull/1431 merged over at our org and happy to get maintainership to do it, and help where we can. Also curious what @brentvatne has to say, given Expo recommend this project and probably want web support over here.

**Comment by mayank-budhiraja** [comment]
Hello @msand - I am happy to contribute to the repo. Let me if I can start by looking at the issues.

**Comment by henrymoulton** [comment]
Just to add here on the back of a tweet with @likern  https://twitter.com/HenryMoulton/status/1388273572523692034

If there's anyone who's seriously up for contributing to this library I'm looking to get some Company Sponsors that use React Native SVG!

**Comment by AkshatJindal1** [comment]
I would like to contribute

**Comment by dlowder-salesforce** [comment]
I can help with this repo as well.

**Comment by vomchik** [comment]
@magicismight does it possible to get access to the repo? I want to help with the review of some small PRs/issues.

**Comment by dilantha111** [comment]
I can help as well. Simply because we are using this in our production application and would like this to continue.

**Comment by pke** [comment]
many (contributors) offered to at lease merge some long running PRs. Have you decided who to give merge rights already @msand?

**Comment by Bibazavr** [comment]
I would like to contribute. And i asked my company for help

**Comment by Victorvikson1996** [comment]
I'm currently available and open to maintain this for free

**Comment by efoken** [comment]
Something new here?

**Comment by Victorvikson1996** [comment]
check again please

**Comment by firstChairCoder** [comment]
Hello @msand if you are still taking maintainers, I would be glad to offer my services as well. I'm not so experienced with this but what I may lack in years of experience, I can make up for in sheer willingness to assist.

**Comment by carlos3g** [comment]
I would like to help, @msand

**Comment by ericanderson** [comment]
Happy to help if it makes progress on outstanding issues.

**Comment by yyskyrr** [comment]
glad to help

**Comment by nivetha12101997** [comment]
got this when running npx react-native run-android. I have already tried gradlew clean.

\node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\RenderableView.java:30: error: cannot find symbol
import com.facebook.react.bridge.ColorPropConverter;
                                ^
  symbol:   class ColorPropConverter
  location: package com.facebook.react.bridge

**Comment by liyanan666** [comment]
When I open it with an Android phone, the app will flash back. Is there a solution？

**Comment by W-Lawless** [comment]
hi, just found this repo and would be happy to help contribute & learn from the open source community. I have some experience using D3 to manage SVG charts and UIs -- I think this would be a great project to apply that bg

**Comment by WoLewicki** [comment]
Hey, new maintainer of the repo here 👋  I think we can close this issue since the maintenance is restored. Of course we are open to contributions to the repo and will gladly collaborate on PRs etc. 🚀  Currently I am focusing on [Fabric implementation](https://github.com/react-native-svg/react-native-svg/pull/1754) so I may be a bit slower to respond. Feel free to comment here if something is wrong and we can always reopen the issue.

**Comment by SebTheRed** [comment]
I would be happy to help! Have someone reach out to me and point me in a direction to code!

**Comment by WoLewicki** [comment]
Hey @SebTheRed ! Thanks for your will to contribute :tada: As for the biggest challenges, there is a PR with filter support: https://github.com/software-mansion/react-native-svg/pull/896 which would need to be refreshed and brought to an end. And if you'd like some easier tasks, there are more than 300 issues right now so there is plenty problems and feature requests to choose from 🚀
