### ISSUE TITLE
Release without jcenter

### ISSUE THREAD

**Issue by pvegh** [react-native-svg/react-native-svg#1573]
Just creating an issue so we can track when a version without jcenter can be pulled for our app releases.

I've seen a pull request for the removal itself:
https://github.com/react-native-svg/react-native-svg/pull/1570

Can it be merged followed by a new release?

**Comment by pvegh** [comment]
Ping after more than a month :)

**Comment by pvegh** [comment]
Ping after 3 months

**Comment by Bibazavr** [comment]
@msand, this is important - jcenter shut down soon

![image](https://user-images.githubusercontent.com/51177449/135027983-a6bf616a-1830-4fe2-b7c7-bfa3845c6330.png)

**Comment by pvegh** [comment]
Can we speed it up? We don't want to wait until the last second. The problem is our builds and releases will break when it happens

**Comment by larsmunkholm** [comment]
Please look into this ASAP

**Comment by aleksamrakovic** [comment]
Ping :)

**Comment by WoLewicki** [comment]
Since https://github.com/react-native-svg/react-native-svg/pull/1570 has been merged, I will close this issue. Feel free to comment if something is wrong and we can reopen it then.
