### ISSUE TITLE
onPress not working on any elements, such as Svg, Circle and Rect in example.

### ISSUE THREAD

**Issue by coldSeattle** [react-native-svg/react-native-svg#1577]
```
<Svg  onPress={() => console.log('pressed')}>
   <Rect fill="red" width="20%" height="20%" onPress={() => console.log('press')} />
   <Circle cx="100" cy="100" r={50} fill="blue" onPress={() => console.log('circle')} />
</Svg>
```

# Bug

onPress not working!!!!!

#### Unexpected behavior

onPress not working on any elements, such as Svg, Circle and Rect in example.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
info Fetching system and libraries information...
(node:15712) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Unable to print environment info.
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.
```

Library version: "12.1.0"

**Comment by coldSeattle** [comment]
Excuse me, the problem was not with library. The problem was with my layout..

onPress working!!

**Comment by arirah-int** [comment]
> Excuse me, the problem was not with library. The problem was with my layout..
> 
> onPress working!!

Can you share how did you design your layout?

**Comment by reterXDark** [comment]
> > Excuse me, the problem was not with library. The problem was with my layout..
> > onPress working!!
> 
> Can you share how did you design your layout?

SOLUTION Give prop to your svg component in which your handling comonent is defined as :           
`          pointerEvents={Platform.OS === 'android' ? 'box-none' : 'auto'}
`

**Comment by reterXDark** [comment]
**### SOLUTION** 
Give prop to your svg component in which your handling comonent is defined as :
`pointerEvents={Platform.OS === 'android' ? 'box-none' : 'auto'}`
