### ISSUE TITLE
Forking the repository produces Invariant Violation: View config getter callback for component `RNSVGGroup` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by fbeccaceci** [react-native-svg/react-native-svg#1583]
# Help

For an app i'm currently working on i need to add some little things to this library, so i tried forking the repository then i added the local dependency to a react native app in package.json like that:

"react-native-svg": "../react-native-svg" 

But if i try to run the app on the android emulator this is the result:

![Screenshot_1620549326](https://user-images.githubusercontent.com/32967519/117565590-4b5d3900-b0b2-11eb-96aa-2cc2cd1e862e.png)

And i can't understand why, installing the library from npm works fine and i haven't changed anything yet

**Comment by andraantariksa** [comment]
How do you solve it?

**Comment by fbeccaceci** [comment]
If i remember right the problem was that i was doing npm install inside the package directory, i tried without doing it and it worked

**Comment by andraantariksa** [comment]
Thank you for your fast response, you're saving my life. It looks like we (or at least I) can't add these package as a direct dependency in a module.
