### ISSUE TITLE
Black SVG filled on Android only

### ISSUE THREAD

**Issue by RigottiG** [react-native-svg/react-native-svg#1591]
# Bug
Some SVG's is filled with black color on Android and iOS is working fine.

#### Unexpected behavior
Filled with black color only on Android's device

## Environment info

React native info output:

```bash
 System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 63.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/opt/nvm/versions/node/v15.8.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.1 - /usr/local/opt/nvm/versions/node/v15.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.0

Describe what you expected to happen:

1. Work fine as iOS

## Short, Self Contained, Correct (Compilable), Example
Android
![image](https://user-images.githubusercontent.com/13246770/119014178-15e80380-b96e-11eb-84bb-e98229a25cc2.png)

iOS is working fine.
![image](https://user-images.githubusercontent.com/13246770/119014256-2ac49700-b96e-11eb-8367-0283039e587f.png)

**Comment by codedbystability** [comment]
any update ?
