### ISSUE TITLE
Found Security Vulnerability under this library

### ISSUE THREAD

**Issue by DVLNarayana** [react-native-svg/react-native-svg#1598]
# Bug

Whitesource is reporting Security Vulnerability for this library, One of the dependence library "css-select@2.1.0" using "css-what@3.2.1" which having  Security Vulnerability.

Solution : update dependence library "css-select" to "4.1.3" which is using latest version of css-what@5.0.1

## Environment info

react-native version : 0.64.2
react-native-svg version: 12.1.1

**Comment by efhan-the-unorthodox** [comment]
I have a same issue as you where i have a high severity vulnerability when I run ```npm audit```

I get this output.
```
css-what  <5.0.1
Severity: high
Denial of Service - https://npmjs.com/advisories/1754
fix available via `npm audit fix --force`
Will install react-native-svg@9.12.0, which is a breaking change
node_modules/css-what
  css-select  <=3.1.2
  Depends on vulnerable versions of css-what
  node_modules/css-select
    react-native-svg  >=9.13.0
    Depends on vulnerable versions of css-select
    node_modules/react-native-svg
      @ui-kitten/components  >=5.0.0-alpha.1
      Depends on vulnerable versions of react-native-svg
      node_modules/@ui-kitten/components
      @ui-kitten/eva-icons  >=5.0.0-alpha.1
      Depends on vulnerable versions of react-native-svg
      node_modules/@ui-kitten/eva-icons

5 high severity vulnerabilities
```

How do you go about updating the dependence library "css-select". Just install it by npm?

**Comment by enahum** [comment]
same issue

**Comment by nikki-cat** [comment]
I am having the exact same issue. Are there plans to fix this?

**Comment by simonxcheng** [comment]
Can you please fix it? We managed to hack package-lock.json to make it work but the css-what is 2 major versions behind. So, it should have a formal dependency update. By the way, the way we hack the package-lock.json can be find here: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions
Please note you need to use **npm ci** instead of **npm install** once you changed package-lock.json.

**Comment by dialex** [comment]
Nice! We still need a new release tho. (_the latest is 12.1.1 from 10 months ago_)
