### ISSUE TITLE
Gradient render disorder

### ISSUE THREAD

**Issue by mnifakram** [react-native-svg/react-native-svg#1600]
# Bug
Gradient is not getting rendered as it should 

This is how it render using `react-native-svg`:

![Simulator Screen Shot - iPhone 12 - 2021-06-10 at 10 50 17](https://user-images.githubusercontent.com/2995199/121504419-e874ff80-c9d9-11eb-990f-eb05b5fb2386.png)

this is how it's supposed to render

![blurry-gradient](https://user-images.githubusercontent.com/2995199/121505829-127af180-c9db-11eb-90ef-dbe9250066b2.png)

this is the svg file: 
```
<svg id="visual" viewBox="0 0 675 900" width="675" height="900" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><defs><filter id="blur1" x="-10%" y="-10%" width="120%" height="120%"><feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood><feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"></feBlend><feGaussianBlur stdDeviation="167" result="effect1_foregroundBlur"></feGaussianBlur></filter></defs><rect width="675" height="900" fill="#6600FF"></rect><g filter="url(#blur1)"><circle cx="260" cy="748" fill="#00CC99" r="371"></circle><circle cx="265" cy="85" fill="#6600FF" r="371"></circle><circle cx="651" cy="263" fill="#00CC99" r="371"></circle><circle cx="519" cy="706" fill="#00CC99" r="371"></circle><circle cx="621" cy="545" fill="#6600FF" r="371"></circle><circle cx="157" cy="369" fill="#00CC99" r="371"></circle></g></svg>
```

I appreciate any kind of help :)

**Comment by vomchik** [comment]
This library doesn't support a Filter feature

**Comment by mnifakram** [comment]
@vomchik thank you for you response, do you know any other alternatives?

**Comment by vomchik** [comment]
you can try to implement it via https://github.com/react-native-svg/react-native-svg#lineargradient

**Comment by mnifakram** [comment]
Sounds good thank you so much
