### ISSUE TITLE
Css-Select peer dependency upgrade

### ISSUE THREAD

**Issue by MohdRizwan7** [react-native-svg/react-native-svg#1660]
Hey,

could you please upgrade the css-select peer dependency to 4.1.3?

Why it is needed

In our security scans nth-check is coming as CVE ,so it will be really helpful if you upgrade the version.

Thank you very much :)

**Comment by StaffanKilnes** [comment]
Same here, showing up as moderate severity in dependabot. Are there any plans to update nth-check to > v2.0.0?

**Comment by smparadeza** [comment]
Same here. It's showing as high severity in Snyk

**Comment by dialex** [comment]
This is a duplicate of https://github.com/react-native-svg/react-native-svg/issues/1622

**Comment by WoLewicki** [comment]
Since https://github.com/react-native-svg/react-native-svg/pull/1692 has been merged and it bumps the `css-select` to `4.2.1`, I think this issue can be safely closed. Feel free to comment here if I am wrong and we can always reopen it.
