### ISSUE TITLE
ClipPath does not animate on Android, works on iOS

### ISSUE THREAD

**Issue by aklemen** [react-native-svg/react-native-svg#1661]
# Bug

I am using [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) together with this library to animate ClipPath.
The animation works perfectly on iOS, but not on Android.

## Environment info

<details>
<summary>React native info output:</summary>

```bash
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 61.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
</details>

Library version: 12.1.1

## Steps To Reproduce

1. `git clone https://github.com/aklemen/ClipPathExample`
2. `cd ClipPathExample`
3. `npm install`
4. `npm run android`

### What should happen:

1. The green rectangle's width should animate from 50 to 200 in 2 seconds (see video below).

https://user-images.githubusercontent.com/56405660/140323636-4f058739-d123-44e2-aaee-26d58a9a9ff4.mp4

## App.tsx
```typescript
import React, {useEffect} from 'react';
import {SafeAreaView, StyleSheet} from 'react-native';
import Animated, {
  useAnimatedProps,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';
import Svg, {ClipPath, Defs, Rect} from 'react-native-svg';

const AnimatedRect = Animated.createAnimatedComponent(Rect);

const App = () => {
  const mainCursorX = useSharedValue<number>(0);

  const HEIGHT = 200;
  const WIDTH = 200;

  const animatedProps = useAnimatedProps(() => {
    return {
      width: mainCursorX.value + 50,
    };
  });

  useEffect(() => {
    mainCursorX.value = withTiming(WIDTH - 50, {duration: 2000});
  });

  return (
    <SafeAreaView style={styles.container}>
      <Svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} width={WIDTH} height={HEIGHT}>
        <Rect
          y="0"
          x="0"
          width={WIDTH}
          height={HEIGHT}
          fill="green"
          clipPath="url(#clipMain)"
        />
        <ClipPath id="clipMain">
          <AnimatedRect
            y="0"
            x="0"
            animatedProps={animatedProps}
            height={HEIGHT}
          />
        </ClipPath>
      </Svg>
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
    alignItems: 'center',
  },
});
```

**Comment by gudwns0102** [comment]
I'm under same issue

**Comment by gurglet** [comment]
This seems to be a regression in 12.1.1. When downgrading to 12.1.0 animated clip paths works properly for me again.

**Comment by aklemen** [comment]
> This seems to be a regression in 12.1.1. When downgrading to 12.1.0 animated clip paths works properly for me again.

This fixed it for me also, thank you! 😄 Fun fact - I just started to work on this issue again today after a month and the animation still didn't work. And then your answer came up. 🪄

**Comment by abdymm** [comment]
hi @aklemen are you still using the 12.1.0 to resolve this issue? have you try use latest version?

**Comment by aklemen** [comment]
> hi @aklemen are you still using the 12.1.0 to resolve this issue? have you try use latest version?

Hey, sorry, I'm not working on that project anymore.
Since this package is now already at `v13.7.0`, this might have gotten fixed. Have you tried it?

**Comment by psquizzle** [comment]
This issue is still relevant as of  "react-native-svg": "^13.8.0", works on iOS no animation on android.

**Comment by nonam4** [comment]
same problem here

**Comment by eprice122** [comment]
same problem as well

**Comment by 0cothucluc** [comment]
I'm having this issue, even with a single clippath component (not animated component), when I update the attribute, the UI does not change so I think it's the reason Android not have animation. My svg version is latest, I tried 12.1.0 but still not working

**Comment by feedthedevil** [comment]
same problem

**Comment by ckaznable** [comment]
same problem and 12.1.0 work for me
