### ISSUE TITLE
Vulnerability , Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by Udith-Murali** [react-native-svg/react-native-svg#1682]
**HIGH SEVERITY** vulnerability

**Regular Expression Denial of Service (ReDoS)**
Vulnerable module: nth-check
Introduced through: css-select@2.1.0
Detailed paths
Introduced through: react-native-svg@12.1.1 › css-select@2.1.0 › nth-check@1.0.2
Remediation: Upgrade to css-select@3.1.1.

Hopefully waiting for a fix in the upcoming update

**Comment by WoLewicki** [comment]
Since #1692 has been merged and it bumps the css-select to 4.2.1, I think this issue can be safely closed. Feel free to comment here if I am wrong and we can always reopen it.
