### ISSUE TITLE
Weird Display in RN V0.68 New Architecture Enabled

### ISSUE THREAD

**Issue by myckhel** [react-native-svg/react-native-svg#1709]
# Bug
Svg does not show in rn v0.68.0-rc.2 with new architecture enabled instead it shows a strange Text of `'RNSVGRect'`
![WhatsApp Image 2022-02-26 at 02 25 32 (1)](https://user-images.githubusercontent.com/34090541/155823387-4204cfa6-97ff-4be8-bd76-1b68f97f5dd6.jpeg) ![WhatsApp Image 2022-02-26 at 02 25 32](https://user-images.githubusercontent.com/34090541/155823396-91c8b1f8-f80a-45c8-8400-1f0c04871ce8.jpeg)

```bash
react-native init CleanProject --version 0.68.0-rc.2
cd CleanProject/
yarn add react-native-svg
modify android/gradle.properties -> and change to newArchEnabled=true
run the app -> react-native run-android
```

## Environment info

React native info output:

```bash
 System:
    OS: macOS 11.6.2
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Memory: 311.86 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0-rc.2 => 0.68.0-rc.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^12.1.1

## Steps To Reproduce

1. react-native init CleanProject --version 0.68.0-rc.2
2. cd CleanProject/
3. yarn add react-native-svg
4. modify android/gradle.properties -> and change to newArchEnabled=true
5. yarn android

Describe what you expected to happen:

1. Display svg correctly

**Comment by myckhel** [comment]
RSSVG Not supported by fabric yet. https://github.com/reactwg/react-native-releases/discussions/13#discussioncomment-2254917

**Comment by kelset** [comment]
@myckhel any chance you can actually prepare some repro code that shows the problem? your repro steps don't contain any code 😅

**Comment by myckhel** [comment]
@kelset Example repo has been created at https://github.com/myckhel/svg-fabric-unsupported
![Screenshot_1646063603](https://user-images.githubusercontent.com/34090541/156014502-9d0a30c6-f8f0-4897-94ff-ad7e5c4f91a4.png)

**Comment by sdevansh96** [comment]
hi,
I am also facing the issue in android using React Native Fabric architecture.
Any way to fix this?

**Comment by pjc0247** [comment]
Same here

**Comment by AlirezaHadjar** [comment]
Apparently react-native-svg does not fully compatible with new architecture yet. #1731

**Comment by pjc0247** [comment]
https://github.com/react-native-svg/react-native-svg/pull/1754

**Comment by andresribeiro** [comment]
> #1754

even after this PR has been merged, some components are still not Fabric compatible

**Comment by WoLewicki** [comment]
I think we can close this issue now since Fabric support is released. Although, if you want to use it on Android in RN version < 0.70.0-rc.3, you need to link the components manually. There is already an issue for how to do it which I plan to resolve ASAP: https://github.com/react-native-svg/react-native-svg/issues/1839. Feel free to comment here if something is wrong and we can always reopen it then.
