### ISSUE TITLE
Error when update to v12.3.0

### ISSUE THREAD

**Issue by yoelianto** [react-native-svg/react-native-svg#1729]
Error: Unable to resolve module ./procedure.json from ********/node_modules/css-select/lib/compile.js: 

None of these files exist:
  * node_modules/css-select/lib/procedure.json(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * node_modules/css-select/lib/procedure.json/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)

**Comment by gramospear** [comment]
Running into the same issue here, any updates on this?

**Comment by Marcuspo** [comment]
up

**Comment by WoLewicki** [comment]
Could you provide a minimal reproduction in a form of a simple repo so we can test the problem in isolation?

**Comment by Marcuspo** [comment]
I had to start a new project and install all lib's too.
the problems has gone.

**Comment by WoLewicki** [comment]
The error message looks like there may be some old caches that needed to be deleted. Since it is not a bug in library, I will close this issue then. Feel free to comment here if I am wrong and we can always reopen it then.

**Comment by michaelcsilva** [comment]
can the recovery procedure be specified more completely please?  I am having this issue too.
