### ISSUE TITLE
Typescript fixes for ComponentClass not including children

### ISSUE THREAD

**Issue by djMax** [react-native-svg/react-native-svg#1755]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@12.3.0` for the project I'm working on.

I don't totally understand the reasons, but React.ComponentClass doesn't seem to include children anymore, so switching to ReactNode seems to make things right. ComponentClass<PropsWithChildren<X>> would work too, but not sure which is more accurate.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/index.d.ts b/node_modules/react-native-svg/src/index.d.ts
index 891a99d..8f5df5e 100644
--- a/node_modules/react-native-svg/src/index.d.ts
+++ b/node_modules/react-native-svg/src/index.d.ts
@@ -265,8 +265,8 @@ export type Ellipse = React.ComponentClass<EllipseProps>;
 export interface GProps extends CommonPathProps, FontProps {
   opacity?: NumberProp;
 }
-export const G: React.ComponentClass<GProps>;
-export type G = React.ComponentClass<GProps>;
+export const G: React.ReactNode<GProps>;
+export type G = React.ReactNode<GProps>;
 
 export interface ForeignObjectProps {
   x?: NumberProp;
@@ -420,8 +420,8 @@ export interface TSpanProps extends CommonPathProps, FontProps {
   rotate?: NumberArray;
   inlineSize?: NumberProp;
 }
-export const TSpan: React.ComponentClass<TSpanProps>;
-export type TSpan = React.ComponentClass<TSpanProps>;
+export const TSpan: React.ReactNode<TSpanProps>;
+export type TSpan = React.ReactNode<TSpanProps>;
 
 export interface TextSpecificProps extends CommonPathProps, FontProps {
   alignmentBaseline?: AlignmentBaseline;
@@ -442,8 +442,8 @@ export interface TextProps extends TextSpecificProps {
   opacity?: NumberProp;
   inlineSize?: NumberProp;
 }
-export const Text: React.ComponentClass<TextProps>;
-export type Text = React.ComponentClass<TextProps>;
+export const Text: React.ReactNode<TextProps>;
+export type Text = React.ReactNode<TextProps>;
 
 export interface TextPathProps extends TextSpecificProps {
   xlinkHref?: string;
@@ -453,8 +453,8 @@ export interface TextPathProps extends TextSpecificProps {
   spacing?: TextPathSpacing;
   midLine?: TextPathMidLine;
 }
-export const TextPath: React.ComponentClass<TextPathProps>;
-export type TextPath = React.ComponentClass<TextPathProps>;
+export const TextPath: React.ReactNode<TextPathProps>;
+export type TextPath = React.ReactNode<TextPathProps>;
 
 export interface UseProps extends CommonPathProps {
   xlinkHref?: string;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by grumpyshiba** [comment]
Also Mask, please

**Comment by TacticCoder** [comment]
Same here

**Comment by WoLewicki** [comment]
Since #1806 has been merged, I think those issues are no longer a problem. Feel free to comment here if I am wrong and we can always reopen it then!

**Comment by lucksp** [comment]
> Since #1806 has been merged, I think those issues are no longer a problem. Feel free to comment here if I am wrong and we can always reopen it then!

@WoLewicki i am seeing this issue:

"react": "18.0.0",
    "expo": "~46.0.19",
    "react-native": "0.69.6",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^1.0.0",

> Type '{ children: Element; fill: string; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<MaskProps, any, any>> & Readonly<MaskProps>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<MaskProps, any, any>> & Readonly<MaskProps>'.ts(2322)
(alias) const Mask: React.ComponentClass<MaskProps, any>
import Mask

**Comment by WoLewicki** [comment]
@lucksp did you upgrade the library version to the one with the fix included? Looking at the PR, It seems to have first appeared in v12.4.1.

**Comment by lucksp** [comment]
> 

AFAIK i did upgrade to the latest version.  However, with an Expo managed workflow, and I am on SDK 46, maybe that's the issue since they generally verify library versions to match their SDK?

**Comment by WoLewicki** [comment]
Yeah, it still had `12.3.0` version of `react-native-svg`, so I am afraid you cannot do much about it. The easiest option would be to maybe use [patch-package](https://www.npmjs.com/package/patch-package) and patch the exact files.
