### ISSUE TITLE
fillOpacity not working with fill="currentColor"

### ISSUE THREAD

**Issue by robrechtme** [react-native-svg/react-native-svg#1802]
# Bug

Using `fillOpacity` in combination with `fill="currentColor"` does not work on iOS and Android. On web it shows expected behaviour.

```tsx
<Svg width="56" height="56" viewBox="0 0 56 56" color="red">

  {/* ✅ Works: renders at 20% opacity */}
  <Rect x="25" y="25" width="20" height="20" rx="4" fill="red" fillOpacity="0.2" />

  {/* ❌ Expected: renders at 20% opacity; Actual: renders at full opacity */}
  <Rect width="20" height="20" rx="4" fill="currentColor" fillOpacity="0.2" />

  {/* ✅ Works: renders at zero opacity */}
  <Rect width="20" height="20" rx="4" fill="currentColor" fillOpacity="0" />
 </Svg>

```

## Environment info

Expo 45 (RN 0.68.2), same on RN bare 0.68.2
Library version: 12.3.0

## Short, Self Contained, Correct (Compilable), Example
https://snack.expo.dev/@robrechtme/bug-react-native-svg-currentcolor

**Comment by robrechtme** [comment]
Same for `opacity` and `strokeOpacity`, they have no effect on iOS and Android.

**Comment by robrechtme** [comment]
Duplicate of https://github.com/react-native-svg/react-native-svg/issues/1345.

**Comment by vladimirevstratov** [comment]
same issue

**Comment by davor-bauk-sh** [comment]
I opened a PR to fix this issue: https://github.com/software-mansion/react-native-svg/pull/2923
