### ISSUE TITLE
How to rotate G with react-native-reanimated

### ISSUE THREAD

**Issue by Pakile** [react-native-svg/react-native-svg#1823]
# Question

How to rotate group with rn-reanimated
I used `rotation` and it works fine on iOS, but on Android not working.
 I tried using transform:

```
const animatedGroup = useAnimatedProps(()=>{
    const coordinates =
      currentItem.value?.type === "group"
        ? currentItem.value.data
        : { x: -10, y: -10, width: 0, height: 0 };

    const  originX = coordinates.x + coordinates.width / 2 // this is anchor x of group
    const originY = coordinates.y + coordinates.height / 2 // this is anchor y of group
    const angle = currentItem.value?.angle || 0;
    
    return {
      transform: [
        { rotate: withTiming(`${angle}deg`) },
      ],
    }
  },[currentItem.value])
```

or

```
transform: [
        { rotateZ: `${angle}deg` },
      ],
```

But couldn't set the anchor.
So how can I anchor the center group when rotated with reanimated
thanks, everyone!

**Comment by sb8378** [comment]
I am also facing same issue
Not able to Rotate G in react native svg
Anyone found the solution?

**Comment by Pakile** [comment]
For the following people who get the same error.
`const animatedGroup = useAnimatedProps(()=>{
    const coordinates =
      currentItem.value?.type === "group"
        ? currentItem.value.data
        : { x: -10, y: -10, width: 0, height: 0 };

    const  originX = coordinates.x + coordinates.width / 2 // this is anchor x of group
    const originY = coordinates.y + coordinates.height / 2 // this is anchor y of group
    const angle = currentItem.value?.angle || 0;
    
    const rotation = interpolate(
      angle,
      [0, 360],
      [0, 360],
      Extrapolation.CLAMP,
    );
    return {
      transform: [
        { translateX: originX },
        { translateY: originY },
        { rotate: `${rotation}deg` },
        { translateX: -originX },
        { translateY: -originY },
      ],
    };
  },[currentItem.value])`
