### ISSUE TITLE
Steps for manually linking 13.0.0 on Android to support Fabric Arch

### ISSUE THREAD

**Issue by nextriot** [react-native-svg/react-native-svg#1839]
The release notes mention the need to manually link on Android for RN versions < 0.70 rc3.
Can someone mention what the steps are exactly?

I'm using RN 0.69.4

**Comment by WoLewicki** [comment]
I made an example repo with the commits adding `react-native-svg` (https://github.com/WoLewicki/ManualLinkingExample) and then enabling new arch on Android manually: https://github.com/WoLewicki/ManualLinkingExample/commit/b28de6943f0a6b77e8618b74b0e99020949b4ee4. It should be enough for the project to compile and work on both platforms with new arch. Could you check if you add the same changes in your project?

**Comment by Bardiamist** [comment]
@WoLewicki Should `react-native-svg` work on 0.69.4 with old architecture without additional steps?

**Comment by WoLewicki** [comment]
Yes, nothing should change there.

**Comment by Bardiamist** [comment]
Thanks, release notes isn't clear so I not tried to update.

Should be need to write:
```
Also, if you use the New Architecture with `react-native` version lesser than `0.70.0-rc.3`
```

Instead of
```
Also, if you use react-native version lesser than `0.70.0-rc.3`
```

**Comment by WoLewicki** [comment]
@Bardiamist I added a note, thanks.

**Comment by nextriot** [comment]
> I made an example repo with the commits adding `react-native-svg` (https://github.com/WoLewicki/ManualLinkingExample) and then enabling new arch on Android manually: https://github.com/WoLewicki/ManualLinkingExample/commit/b28de6943f0a6b77e8618b74b0e99020949b4ee4. It should be enough for the project to compile and work on both platforms with new arch. Could you check if you add the same changes in your project?

Thanks a bunch @WoLewicki! Worked perfectly 😊
