### ISSUE TITLE
react-native-svg >= 13 does not work with react-native's Animated API on Android

### ISSUE THREAD

**Issue by hsjoberg** [react-native-svg/react-native-svg#1852]
This might be a dupe of #1845, but I am not certain. Feel free to close if you know that it's a dupe.

# Bug

On react-native-svg >= 13 on Android, the Animated API seems to not work as it should.
It's giving the following error when trying to animate an attribute:

```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
```

## Environment info

I am running react-native 0.69.5 and react-native-svg 13.1.0 (on Android SDK 33)

I am not using the new architecture.

## Steps To Reproduce

Render the following component: 

```JSX
import React, { useEffect, useRef } from "react";
import { Animated } from "react-native";
import Svg, { Circle } from "react-native-svg";

const AnimatedCircle = Animated.createAnimatedComponent(Circle);

export function Crash() {
  const circleRadius = useRef(new Animated.Value(55)).current;

  useEffect(() => {
    Animated.spring(circleRadius, {
      toValue: 80,
      friction: 4.5,
      useNativeDriver: true,
    }).start();
  }, []);


  return (
    <Svg width={200} height={200}>
      <AnimatedCircle
        cx={100}
        cy={100}
        fill="#ff0000"
        r={circleRadius}
      />
    </Svg>
  );
}
```

App will instantly crash when animation starts.

**Comment by buschco** [comment]
@WoLewicki Can you point out why you think it is a duplicate? 
#1845 seems to be about `react-native-svg` used with `react-native-reanimated` but this issue is about `react-native-svg` with `react-native`s `Animated` API.

**Comment by WoLewicki** [comment]
I believe the root of the problem is the same, not going through `render`/`setNativeProps` method which does not transforming the props to the format accepted by the native code.

**Comment by hsjoberg** [comment]
This issue was fixed by https://github.com/software-mansion/react-native-svg/releases/tag/v13.4.0, so it seems likely that this ended up being a dupe.

Though admittedly I was very confused about all the different libs being involved here, which is why I opened the issue in the first place, thinking it was different to @1845.
