### ISSUE TITLE
v13 don't update layout on Android

### ISSUE THREAD

**Issue by Bardiamist** [react-native-svg/react-native-svg#1859]
# Bug

After update `react-native-svg` from `12.4.4` to `13.1.0` layout change don't work properly on Android on old architecture

Tried on react-native `0.69.5` and `0.70.0` and Android 9
No problems on iOS

## Steps To Reproduce

1. git clone https://github.com/Bardiamist/svg
2. cd svg
3. yarn
4. Run project on Android 9 (API 28)
5. Press `Toggle` button (should work good)
6. Press `Toggle` button again (should to show previous layout but dosn't)

Ineteresting that if remove `verticalLines` then layout will not update even on first `Toggle` button press

**Comment by WoLewicki** [comment]
@Bardiamist can you check if https://github.com/react-native-svg/react-native-svg/pull/1864 resolves the issue?

**Comment by Bardiamist** [comment]
> @Bardiamist can you check if #1864 resolves the issue?

Tried, looks good

**Comment by Bardiamist** [comment]
Fixed in 13.2.0
