### ISSUE TITLE
Android v13 breaks victory-native

### ISSUE THREAD

**Issue by mordechaim** [react-native-svg/react-native-svg#1861]
A [recent fix](https://github.com/react-native-svg/react-native-svg/pull/1542#) to retain the icons while transitioning on Android broke victory-native. 
Updating props will freeze the entire UI.

I did mention in the PR a better fix to the issue
https://github.com/react-native-svg/react-native-svg/pull/1542#issuecomment-1183404676

Reproduction: https://github.com/mordechaim/SvgVictoryTest

There are 2 branches
-  `svg@12+patch` uses the patch I posted up here and works flawlessly
- `svg@13` uses the latest version without the patch, the UI locks up after 3 button presses

_Originally posted by @mordechaim in https://github.com/react-native-svg/react-native-svg/issues/1542#issuecomment-1231973168_

**Comment by Minishlink** [comment]
I can confirm this problem that can appear when you have a component that render an icon or the other depending on a condition. A temporary workaround if you don't want to downgrade is adding a `key` prop. (but if you use third party libraries like victory it becomes a bit cumbersome)

```tsx 
export const PlayPauseIcon: FunctionComponent<Props> = ({
  isPaused,
  size = DEFAULT_SIZE,
  color,
}) => {
  const { colors } = useTheme();

  if (!isPaused) {
    return (
      <Svg key="play" width={size} height={size} viewBox="0 0 48 48" fill="none">
        <Rect width="48" height="48" fill={color || colors.white} fillOpacity="0.01" />
        <Path
          d="M16 12V36"
          stroke={color || colors.white}
          strokeWidth="8"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <Path
          d="M32 12V36"
          stroke={color || colors.white}
          strokeWidth="8"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </Svg>
    );
  }

  return (
    <Svg key="paused" width={size} height={size} viewBox="0 0 48 48" fill="none">
      <Rect width="48" height="48" fill={color || colors.white} fillOpacity="0.01" />
      <Path
        d="M15 24V11.8756L25.5 17.9378L36 24L25.5 30.0622L15 36.1244V24Z"
        fill={color || colors.white}
        stroke={color || colors.white}
        strokeWidth="8"
        strokeLinejoin="round"
      />
    </Svg>
  );
};
```

**Comment by mordechaim** [comment]
Using a key is unacceptable. This will unmount and remount the entire component on each render, and for victory this is a huge overhead to an already heavy render logic

**Comment by WoLewicki** [comment]
@mordechaim @Minishlink can you check if applying https://github.com/react-native-svg/react-native-svg/pull/1864 fixes your issues?

**Comment by mordechaim** [comment]
I can confirm that #1864 solves this issue.

**Comment by WoLewicki** [comment]
I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by LucasHimelfarb** [comment]
My implementation of Victory is getting random crashes like it:
<img width="381" alt="Screenshot 2023-10-10 at 11 15 56" src="https://github.com/software-mansion/react-native-svg/assets/46998551/f44f6012-1f74-4c19-a694-c6b5308f8dbc">


Tried doing react-native-svg overrides, doing downgrades but nothing works
