### ISSUE TITLE
Bump package.json to 13.1.1

### ISSUE THREAD

**Issue by darigoce** [react-native-svg/react-native-svg#1868]
Right now when you npm install you will get the old version of the files, which still contain the FabricEnabledViewGroup https://github.com/react-native-svg/react-native-svg/issues/1854

Note:
Even after npm cache clean and removing the node_modules folder I still get the old files

**Comment by WoLewicki** [comment]
It will be available with the new release, which I am planning on doing today. It is an expected behavior and should not be considered an issue. I will close it then. Feel free to comment here if something is wrong and we can always reopen it then.
