### ISSUE TITLE
currentColor not work as expected in a transform svg in 13.2.0

### ISSUE THREAD

**Issue by GaelCO** [react-native-svg/react-native-svg#1872]
Our app use a svg as a component, with react-native-svg-transformer.
This svg has a path with style="fill:currentColor".

This usage works fine with react-native-svg 13.1.0.
But, after upgrade to 13.2.0, the coloration was weird. Invisible (android) or bad color (ios)

**Comment by GaelCO** [comment]
In my case, I no longer have this issue. I stopped using 'react-native-svg-transformer' to directly build an SVG component.

**Comment by Risovas** [comment]
I'm also having this problem, updated to 13.2.0 and all SVG's used with `react-native-svg-transformer` became transparent on Android

**Comment by jimbofoo** [comment]
Please see https://github.com/react-native-svg/react-native-svg/issues/1875#issuecomment-1253784738 on how we fixed it

**Comment by GaelCO** [comment]
Seems to be fixed with 13.3.0
