### ISSUE TITLE
Version 13.2 does not respect color codes. Downgrading to 13.1 fixes issue.

### ISSUE THREAD

**Issue by MyPalVikram** [react-native-svg/react-native-svg#1875]
I'm using the Iconoir icon package and at first, I thought the issue was with the package and reported it as an issue there. But I realized it was version 13.2 that wasn't respecting the color codes and the downgrade to 13.1 fixed that issue.

The issue I posted with Iconoir:

https://github.com/iconoir-icons/iconoir/issues/198

**Comment by WoLewicki** [comment]
I tested it in version `13.1.0` and it does not work for me there. It might be caused by this line: https://github.com/iconoir-icons/iconoir/blob/50a9c03f799bfeaec08bd7dbb78ea2f424eba3b5/packages/iconoir-react-native/src/Mail.tsx#L18 since `Svg` does not accept `currentColor` value as `color` prop. It seems like a bug in the library. As a fix, you can pass your own value as `color` prop.

**Comment by zolbooo** [comment]
I also can confirm that `currentColor` is broken on RNSVG 13.2. We are using icons with `fill="currentColor"` and they do not respect color prop passed to Svg on the new version.

**Comment by WoLewicki** [comment]
@zolbooo can you provide a repo with example which works on the previous version and does not on `13.2.0`? It would greatly reduce the time we need to spend on it. Also, it does not work for both `iOS` and `Android`?

**Comment by zolbooo** [comment]
> @zolbooo can you provide a repo with example which works on the previous version and does not on `13.2.0`? It would greatly reduce the time we need to spend on it. Also, it does not work for both `iOS` and `Android`?

I tested in on iOS. Currently I am far away from my laptop, so I'm gonna give you an example later 😁.

**Comment by jimbofoo** [comment]
In our case this was solved by disabling the following  svgo optimizations:
```
module.exports = {
  replaceAttrValues: {
    "#000" : '{props.color}'
  },
  svgoConfig: {
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            removeUselessStrokeAndFill: false,
            removeUnknownsAndDefaults: false
          }
        }
      },
      {
        name: "removeAttrs",
        params: {
          attrs: ".*#sodipodi:docname#.*",
          elemSeparator: "#"
        }
      }
    ]
  }
}
```

**Comment by zolbooo** [comment]
Here is the repro: https://github.com/zolbooo/rnsvg-color-error-repro

I passed `color="blue"` to the Svg component but icon is red 🤔.

<img width="551" alt="Screen Shot 2022-09-21 at 23 08 22" src="https://user-images.githubusercontent.com/33338165/191590065-fded2c71-2863-47ba-a95d-43c86d0a976a.png">

**Comment by zolbooo** [comment]
Quick update: on Android some icons aren't even shown.

**Comment by FadiAboMsalam** [comment]
+1

**Comment by WoLewicki** [comment]
Can you check if https://github.com/react-native-svg/react-native-svg/pull/1887 fixes the issue?

**Comment by zolbooo** [comment]
> Can you check if #1887 fixes the issue?

Yup, it works on both Android and iOS correctly now. Great job! 🎉
